window.OUTPLAN_REPORT = {
  "meta": {
    "title": "Outplan · Google Ads · Histórico 2026",
    "accountId": "1826573172",
    "sourceGeneratedAt": "2026-10-07T03:11:17.581Z",
    "reportGeneratedAt": "2026-10-07T18:32:18.844Z",
    "startDate": "2026-02-18",
    "endDate": "2026-10-06",
    "requestedEndDate": "2026-10-06",
    "partialMonth": "2026-10",
    "currency": "BRL",
    "timeZone": "America/Sao_Paulo"
  },
  "totals": {
    "impressions": 33181,
    "clicks": 1999,
    "spend": 21141.85,
    "leads": 43,
    "websiteLeads": 40,
    "hostedLeads": 3,
    "ctr": 0.0602,
    "cpc": 10.58,
    "leadRate": 0.0215,
    "cpl": 491.67
  },
  "monthly": [
    {
      "key": "2026-02",
      "label": "Fev 2026",
      "partial": false,
      "impressions": 1207,
      "clicks": 239,
      "spend": 49.57,
      "leads": 0,
      "websiteLeads": 0,
      "hostedLeads": 0,
      "ctr": 0.198,
      "cpc": 0.21,
      "leadRate": 0,
      "cpl": null,
      "platformConversions": 4,
      "allConversions": 4,
      "searchImpressionShare": 0.2286,
      "searchBudgetLostShare": 0.1619,
      "searchRankLostShare": 0.6095,
      "leadsChange": null,
      "spendChange": null,
      "cplChange": null,
      "clicksChange": null
    },
    {
      "key": "2026-03",
      "label": "Mar 2026",
      "partial": false,
      "impressions": 7447,
      "clicks": 222,
      "spend": 2644.35,
      "leads": 7,
      "websiteLeads": 7,
      "hostedLeads": 0,
      "ctr": 0.0298,
      "cpc": 11.91,
      "leadRate": 0.0315,
      "cpl": 377.76,
      "platformConversions": 70,
      "allConversions": 233,
      "searchImpressionShare": 0.0999,
      "searchBudgetLostShare": 0.5103,
      "searchRankLostShare": 0.4598,
      "leadsChange": null,
      "spendChange": 52.3458,
      "cplChange": null,
      "clicksChange": -0.0711
    },
    {
      "key": "2026-04",
      "label": "Abr 2026",
      "partial": false,
      "impressions": 4964,
      "clicks": 242,
      "spend": 3082.09,
      "leads": 11,
      "websiteLeads": 11,
      "hostedLeads": 0,
      "ctr": 0.0488,
      "cpc": 12.74,
      "leadRate": 0.0455,
      "cpl": 280.19,
      "platformConversions": 11,
      "allConversions": 253,
      "searchImpressionShare": 0.0999,
      "searchBudgetLostShare": 0.2328,
      "searchRankLostShare": 0.7355,
      "leadsChange": 0.5714,
      "spendChange": 0.1655,
      "cplChange": -0.2583,
      "clicksChange": 0.0901
    },
    {
      "key": "2026-05",
      "label": "Mai 2026",
      "partial": false,
      "impressions": 3953,
      "clicks": 294,
      "spend": 2988.65,
      "leads": 7,
      "websiteLeads": 7,
      "hostedLeads": 0,
      "ctr": 0.0744,
      "cpc": 10.17,
      "leadRate": 0.0238,
      "cpl": 426.95,
      "platformConversions": 7,
      "allConversions": 462.67,
      "searchImpressionShare": 0.0999,
      "searchBudgetLostShare": 0.216,
      "searchRankLostShare": 0.741,
      "leadsChange": -0.3636,
      "spendChange": -0.0303,
      "cplChange": 0.5238,
      "clicksChange": 0.2149
    },
    {
      "key": "2026-06",
      "label": "Jun 2026",
      "partial": false,
      "impressions": 3653,
      "clicks": 231,
      "spend": 3046.12,
      "leads": 8,
      "websiteLeads": 8,
      "hostedLeads": 0,
      "ctr": 0.0632,
      "cpc": 13.19,
      "leadRate": 0.0346,
      "cpl": 380.77,
      "platformConversions": 8,
      "allConversions": 267.33,
      "searchImpressionShare": 0.0999,
      "searchBudgetLostShare": 0.333,
      "searchRankLostShare": 0.6096,
      "leadsChange": 0.1429,
      "spendChange": 0.0192,
      "cplChange": -0.1082,
      "clicksChange": -0.2143
    },
    {
      "key": "2026-07",
      "label": "Jul 2026",
      "partial": false,
      "impressions": 4633,
      "clicks": 241,
      "spend": 3062.33,
      "leads": 4,
      "websiteLeads": 4,
      "hostedLeads": 0,
      "ctr": 0.052,
      "cpc": 12.71,
      "leadRate": 0.0166,
      "cpl": 765.58,
      "platformConversions": 4,
      "allConversions": 161,
      "searchImpressionShare": 0.0999,
      "searchBudgetLostShare": 0.2872,
      "searchRankLostShare": 0.6551,
      "leadsChange": -0.5,
      "spendChange": 0.0053,
      "cplChange": 1.0106,
      "clicksChange": 0.0433
    },
    {
      "key": "2026-08",
      "label": "Ago 2026",
      "partial": false,
      "impressions": 4590,
      "clicks": 249,
      "spend": 2967.01,
      "leads": 1,
      "websiteLeads": 1,
      "hostedLeads": 0,
      "ctr": 0.0542,
      "cpc": 11.92,
      "leadRate": 0.004,
      "cpl": 2967.01,
      "platformConversions": 1,
      "allConversions": 83,
      "searchImpressionShare": 0.0999,
      "searchBudgetLostShare": 0.2213,
      "searchRankLostShare": 0.6961,
      "leadsChange": -0.75,
      "spendChange": -0.0311,
      "cplChange": 2.8755,
      "clicksChange": 0.0332
    },
    {
      "key": "2026-09",
      "label": "Set 2026",
      "partial": false,
      "impressions": 2321,
      "clicks": 239,
      "spend": 2736.02,
      "leads": 5,
      "websiteLeads": 2,
      "hostedLeads": 3,
      "ctr": 0.103,
      "cpc": 11.45,
      "leadRate": 0.0209,
      "cpl": 547.2,
      "platformConversions": 5,
      "allConversions": 31,
      "searchImpressionShare": 0.1243,
      "searchBudgetLostShare": 0.3691,
      "searchRankLostShare": 0.5066,
      "leadsChange": 4,
      "spendChange": -0.0779,
      "cplChange": -0.8156,
      "clicksChange": -0.0402
    },
    {
      "key": "2026-10",
      "label": "Out 2026",
      "partial": true,
      "impressions": 413,
      "clicks": 42,
      "spend": 565.71,
      "leads": 0,
      "websiteLeads": 0,
      "hostedLeads": 0,
      "ctr": 0.1017,
      "cpc": 13.47,
      "leadRate": 0,
      "cpl": null,
      "platformConversions": 0,
      "allConversions": 0,
      "searchImpressionShare": 0.1057,
      "searchBudgetLostShare": 0.4239,
      "searchRankLostShare": 0.4705,
      "leadsChange": -1,
      "spendChange": -0.7932,
      "cplChange": null,
      "clicksChange": -0.8243
    }
  ],
  "phases": [
    {
      "id": "launch",
      "period": "18 fev–mar",
      "title": "Setup do funil e início da operação",
      "summary": "Fevereiro foi dedicado à construção da base do projeto: funil de marketing, automações, CRM e mensuração. Em março, as campanhas entraram na etapa de validação e começaram a gerar os primeiros leads.",
      "landingPages": [
        "A",
        "B"
      ],
      "actions": [
        "Construção do funil de marketing e configuração das automações",
        "Integração com o CRM Pipedrive e organização do fluxo dos leads",
        "Implementação do rastreamento avançado server-side",
        "Início dos testes de campanha e das landing pages A e B"
      ],
      "spend": 2693.92,
      "leads": 7,
      "websiteLeads": 7,
      "hostedLeads": 0,
      "clicks": 461,
      "cpl": 384.85,
      "leadRate": 0.0152
    },
    {
      "id": "productive",
      "period": "abr–jun",
      "title": "Mais volume e qualificação do público",
      "summary": "A leitura dos primeiros leads mostrou uma oportunidade de aumentar a aderência ao perfil desejado. As campanhas ficaram mais segmentadas e a comunicação passou a usar uma linguagem mais técnica de Procurement.",
      "landingPages": [
        "C",
        "D"
      ],
      "actions": [
        "Refinamento da segmentação a partir do perfil dos leads recebidos",
        "Inclusão de critérios voltados a operações de maior porte",
        "Novas headlines e argumentos voltados a Procurement",
        "Testes com as versões C e D da landing page"
      ],
      "spend": 9116.86,
      "leads": 26,
      "websiteLeads": 26,
      "hostedLeads": 0,
      "clicks": 767,
      "cpl": 350.65,
      "leadRate": 0.0339
    },
    {
      "id": "qualification",
      "period": "jul–ago",
      "title": "Segmentação para empresas de grande porte",
      "summary": "Campanhas e landing page ficaram mais seletivas, priorizando grandes empresas e operações com aproximadamente R$ 10 milhões anuais em compras.",
      "landingPages": [
        "E"
      ],
      "actions": [
        "Refinamento de público e termos para reduzir contatos fora do perfil",
        "Versão E com foco em porte, governança e alto volume de compras"
      ],
      "spend": 6029.34,
      "leads": 5,
      "websiteLeads": 5,
      "hostedLeads": 0,
      "clicks": 490,
      "cpl": 1205.87,
      "leadRate": 0.0102
    },
    {
      "id": "iteration",
      "period": "set",
      "title": "Nova proposta e recuperação de volume",
      "summary": "A versão G reforçou Procurement, SRM e savings com uma apresentação mais humana. O mês voltou a registrar cinco leads.",
      "landingPages": [
        "G"
      ],
      "actions": [
        "Nova narrativa de Procurement e SRM integrada ao ERP",
        "Teste conjunto do formulário do site e do formulário hospedado pelo Google"
      ],
      "spend": 2736.02,
      "leads": 5,
      "websiteLeads": 2,
      "hostedLeads": 3,
      "clicks": 239,
      "cpl": 547.2,
      "leadRate": 0.0209
    },
    {
      "id": "next",
      "period": "1–6 out",
      "title": "Abertura controlada do público",
      "summary": "Em outubro, o recorte por spend anual foi flexibilizado para não limitar a entrega somente às empresas na faixa de R$ 10 milhões. O objetivo é ampliar o volume de leads sem perder aderência ao perfil qualificado.",
      "landingPages": [
        "G atual"
      ],
      "actions": [
        "Ampliação do alcance para empresas com diferentes faixas de spend anual",
        "Manutenção dos filtros de intenção e aderência ao perfil de compra B2B",
        "Grupos reorganizados por intenção de busca",
        "Revisão das correspondências e do acompanhamento de conversões"
      ],
      "spend": 565.71,
      "leads": 0,
      "websiteLeads": 0,
      "hostedLeads": 0,
      "clicks": 42,
      "cpl": null,
      "leadRate": 0
    }
  ],
  "campaigns": [
    {
      "id": "22474772611",
      "name": "[VENDA] OBC versão 1",
      "status": "PAUSED",
      "primaryStatus": "PAUSED",
      "bidding": "TARGET_SPEND",
      "channel": "SEARCH",
      "firstActive": "2026-02-18",
      "lastActive": "2026-02-19",
      "impressions": 1183,
      "clicks": 235,
      "spend": 18.11,
      "leads": 0,
      "cpl": null
    },
    {
      "id": "23609286623",
      "name": "[Pesquisa] [CLIQUES] Outbuycenter - 01",
      "status": "PAUSED",
      "primaryStatus": "PAUSED",
      "bidding": "TARGET_SPEND",
      "channel": "SEARCH",
      "firstActive": "2026-02-28",
      "lastActive": "2026-03-09",
      "impressions": 2538,
      "clicks": 59,
      "spend": 502.34,
      "leads": 0,
      "cpl": null
    },
    {
      "id": "23634855253",
      "name": "[Pesquisa] [CONVERSÕES] Outbuycenter - 02",
      "status": "ENABLED",
      "primaryStatus": "LIMITED",
      "bidding": "MAXIMIZE_CONVERSIONS",
      "channel": "SEARCH",
      "firstActive": "2026-03-06",
      "lastActive": "2026-10-06",
      "impressions": 29460,
      "clicks": 1705,
      "spend": 20621.41,
      "leads": 43,
      "cpl": 479.57
    }
  ],
  "adGroups": [
    {
      "id": "196699626169",
      "name": "CJ01 - Categoria e Soluções [Fundo de Funil]",
      "status": "ENABLED",
      "firstMonth": "2026-03",
      "lastMonth": "2026-10",
      "impressions": 21261,
      "clicks": 1176,
      "spend": 15276.92,
      "leads": 30,
      "websiteLeads": 29,
      "hostedLeads": 1,
      "ctr": 0.0553,
      "leadRate": 0.0255,
      "cpl": 509.23
    },
    {
      "id": "196699626129",
      "name": "CJ02 - Concorrentes",
      "status": "ENABLED",
      "firstMonth": "2026-03",
      "lastMonth": "2026-10",
      "impressions": 7244,
      "clicks": 314,
      "spend": 4230.04,
      "leads": 11,
      "websiteLeads": 9,
      "hostedLeads": 2,
      "ctr": 0.0433,
      "leadRate": 0.035,
      "cpl": 384.55
    },
    {
      "id": "199296966229",
      "name": "CJ00 - Marca",
      "status": "ENABLED",
      "firstMonth": "2026-08",
      "lastMonth": "2026-10",
      "impressions": 955,
      "clicks": 215,
      "spend": 1114.45,
      "leads": 2,
      "websiteLeads": 2,
      "hostedLeads": 0,
      "ctr": 0.2251,
      "leadRate": 0.0093,
      "cpl": 557.23
    }
  ],
  "landingPages": [
    {
      "url": "https://outbuycenter.software/",
      "label": "Página principal",
      "kind": "Página base",
      "firstMonth": "2026-02",
      "lastMonth": "2026-10",
      "impressions": 43195,
      "clicks": 1563,
      "spend": 18250.38,
      "leads": 37,
      "websiteLeads": 34,
      "hostedLeads": 3,
      "ctr": 0.0362,
      "cpl": 493.25
    },
    {
      "url": "https://outbuycenter.software/#B2B",
      "label": "Página principal · âncora B2B",
      "kind": "Âncora na mesma página",
      "firstMonth": "2026-02",
      "lastMonth": "2026-10",
      "impressions": 9754,
      "clicks": 143,
      "spend": 2145.93,
      "leads": 6,
      "websiteLeads": 6,
      "hostedLeads": 0,
      "ctr": 0.0147,
      "cpl": 357.66
    },
    {
      "url": "https://outbuycenter.software/#demo",
      "label": "Página principal · âncora demo",
      "kind": "Âncora na mesma página",
      "firstMonth": "2026-02",
      "lastMonth": "2026-10",
      "impressions": 13679,
      "clicks": 47,
      "spend": 616.16,
      "leads": 0,
      "websiteLeads": 0,
      "hostedLeads": 0,
      "ctr": 0.0034,
      "cpl": null
    },
    {
      "url": "https://outbuycenter.software/#ERP",
      "label": "Página principal · âncora ERP",
      "kind": "Âncora na mesma página",
      "firstMonth": "2026-02",
      "lastMonth": "2026-10",
      "impressions": 9162,
      "clicks": 9,
      "spend": 91.89,
      "leads": 0,
      "websiteLeads": 0,
      "hostedLeads": 0,
      "ctr": 0.001,
      "cpl": null
    },
    {
      "url": "https://outbuycenter.software/#compras",
      "label": "Página principal · âncora compras",
      "kind": "Âncora na mesma página",
      "firstMonth": "2026-02",
      "lastMonth": "2026-10",
      "impressions": 7261,
      "clicks": 2,
      "spend": 19.38,
      "leads": 0,
      "websiteLeads": 0,
      "hostedLeads": 0,
      "ctr": 0.0003,
      "cpl": null
    },
    {
      "url": "https://www.outplan.com.br",
      "label": "Site institucional antigo",
      "kind": "Domínio anterior",
      "firstMonth": "2026-02",
      "lastMonth": "2026-02",
      "impressions": 1183,
      "clicks": 235,
      "spend": 18.11,
      "leads": 0,
      "websiteLeads": 0,
      "hostedLeads": 0,
      "ctr": 0.1986,
      "cpl": null
    }
  ],
  "search": {
    "topLeadTerms": [
      {
        "text": "outbuycenter",
        "matchedKeyword": "outbuycenter",
        "impressions": 1574,
        "clicks": 438,
        "spend": 2675.03,
        "leads": 10,
        "ctr": 0.2783,
        "cpl": 267.5
      },
      {
        "text": "nimbi",
        "matchedKeyword": "nimbi",
        "impressions": 3189,
        "clicks": 71,
        "spend": 1123.14,
        "leads": 2,
        "ctr": 0.0223,
        "cpl": 561.57
      },
      {
        "text": "robo de licitação",
        "matchedKeyword": "E-procurement",
        "impressions": 6,
        "clicks": 1,
        "spend": 7.95,
        "leads": 1,
        "ctr": 0.1667,
        "cpl": 7.95
      },
      {
        "text": "email setor de compras",
        "matchedKeyword": "E-procurement",
        "impressions": 2,
        "clicks": 1,
        "spend": 19.33,
        "leads": 1,
        "ctr": 0.5,
        "cpl": 19.33
      },
      {
        "text": "alibaba",
        "matchedKeyword": "portal de compras b2b",
        "impressions": 35,
        "clicks": 3,
        "spend": 27.34,
        "leads": 1,
        "ctr": 0.0857,
        "cpl": 27.34
      },
      {
        "text": "mercado eletrônico me",
        "matchedKeyword": "alternativa mercado eletronico",
        "impressions": 61,
        "clicks": 2,
        "spend": 28.41,
        "leads": 1,
        "ctr": 0.0328,
        "cpl": 28.41
      },
      {
        "text": "e fornecedor",
        "matchedKeyword": "Ferramenta de E-procurement",
        "impressions": 3,
        "clicks": 1,
        "spend": 30.01,
        "leads": 1,
        "ctr": 0.3333,
        "cpl": 30.01
      },
      {
        "text": "portal nimbi",
        "matchedKeyword": "nimbi",
        "impressions": 34,
        "clicks": 2,
        "spend": 34.03,
        "leads": 1,
        "ctr": 0.0588,
        "cpl": 34.03
      },
      {
        "text": "empresa de compras",
        "matchedKeyword": "E-procurement",
        "impressions": 14,
        "clicks": 1,
        "spend": 38.49,
        "leads": 1,
        "ctr": 0.0714,
        "cpl": 38.49
      },
      {
        "text": "odoo site",
        "matchedKeyword": "software srm",
        "impressions": 2,
        "clicks": 1,
        "spend": 43.91,
        "leads": 1,
        "ctr": 0.5,
        "cpl": 43.91
      },
      {
        "text": "nimbi portal",
        "matchedKeyword": "nimbi",
        "impressions": 39,
        "clicks": 4,
        "spend": 55.44,
        "leads": 1,
        "ctr": 0.1026,
        "cpl": 55.44
      },
      {
        "text": "mapa dos fornecedores",
        "matchedKeyword": "software srm",
        "impressions": 26,
        "clicks": 4,
        "spend": 75.14,
        "leads": 1,
        "ctr": 0.1538,
        "cpl": 75.14
      }
    ],
    "topNoLeadTerms": [
      {
        "text": "outplan",
        "matchedKeyword": "outplan",
        "impressions": 393,
        "clicks": 65,
        "spend": 558.73,
        "leads": 0,
        "ctr": 0.1654,
        "cpl": null
      },
      {
        "text": "odoo com em português",
        "matchedKeyword": "software de compras",
        "impressions": 52,
        "clicks": 8,
        "spend": 250.19,
        "leads": 0,
        "ctr": 0.1538,
        "cpl": null
      },
      {
        "text": "e procurement",
        "matchedKeyword": "sistema de e-procurement",
        "impressions": 313,
        "clicks": 14,
        "spend": 216.38,
        "leads": 0,
        "ctr": 0.0447,
        "cpl": null
      },
      {
        "text": "eprocurement",
        "matchedKeyword": "sistema de e-procurement",
        "impressions": 80,
        "clicks": 3,
        "spend": 196.58,
        "leads": 0,
        "ctr": 0.0375,
        "cpl": null
      },
      {
        "text": "b2b",
        "matchedKeyword": "E-procurement",
        "impressions": 399,
        "clicks": 17,
        "spend": 179.91,
        "leads": 0,
        "ctr": 0.0426,
        "cpl": null
      },
      {
        "text": "nimbi cadastro fornecedor",
        "matchedKeyword": "nimbi",
        "impressions": 88,
        "clicks": 10,
        "spend": 157.31,
        "leads": 0,
        "ctr": 0.1136,
        "cpl": null
      },
      {
        "text": "sistema de compras",
        "matchedKeyword": "software de compras",
        "impressions": 79,
        "clicks": 6,
        "spend": 156.3,
        "leads": 0,
        "ctr": 0.0759,
        "cpl": null
      },
      {
        "text": "ata360",
        "matchedKeyword": "Ferramenta de E-procurement",
        "impressions": 1,
        "clicks": 1,
        "spend": 120.29,
        "leads": 0,
        "ctr": 1,
        "cpl": null
      },
      {
        "text": "mercado eletrônico",
        "matchedKeyword": "E-procurement",
        "impressions": 110,
        "clicks": 6,
        "spend": 119.32,
        "leads": 0,
        "ctr": 0.0545,
        "cpl": null
      },
      {
        "text": "fornece",
        "matchedKeyword": "E-procurement",
        "impressions": 63,
        "clicks": 6,
        "spend": 116.22,
        "leads": 0,
        "ctr": 0.0952,
        "cpl": null
      }
    ],
    "topMatchedKeywords": [
      {
        "text": "outbuycenter",
        "matchedKeyword": null,
        "impressions": 2240,
        "clicks": 474,
        "spend": 3589.42,
        "leads": 10,
        "ctr": 0.2116,
        "cpl": 358.94
      },
      {
        "text": "nimbi",
        "matchedKeyword": null,
        "impressions": 4720,
        "clicks": 180,
        "spend": 2473.46,
        "leads": 7,
        "ctr": 0.0381,
        "cpl": 353.35
      },
      {
        "text": "E-procurement",
        "matchedKeyword": null,
        "impressions": 3997,
        "clicks": 140,
        "spend": 2052.42,
        "leads": 5,
        "ctr": 0.035,
        "cpl": 410.48
      },
      {
        "text": "portal de compras b2b",
        "matchedKeyword": null,
        "impressions": 414,
        "clicks": 32,
        "spend": 448.05,
        "leads": 1,
        "ctr": 0.0773,
        "cpl": 448.05
      },
      {
        "text": "sistema de gestão de fornecedores",
        "matchedKeyword": null,
        "impressions": 763,
        "clicks": 30,
        "spend": 427.17,
        "leads": 1,
        "ctr": 0.0393,
        "cpl": 427.17
      },
      {
        "text": "software srm",
        "matchedKeyword": null,
        "impressions": 708,
        "clicks": 14,
        "spend": 268.13,
        "leads": 1,
        "ctr": 0.0198,
        "cpl": 268.13
      },
      {
        "text": "proxpect",
        "matchedKeyword": null,
        "impressions": 987,
        "clicks": 14,
        "spend": 209.25,
        "leads": 1,
        "ctr": 0.0142,
        "cpl": 209.25
      },
      {
        "text": "Ferramenta de E-procurement",
        "matchedKeyword": null,
        "impressions": 191,
        "clicks": 7,
        "spend": 194.02,
        "leads": 1,
        "ctr": 0.0366,
        "cpl": 194.02
      },
      {
        "text": "sistema de e-procurement",
        "matchedKeyword": null,
        "impressions": 1049,
        "clicks": 55,
        "spend": 830.24,
        "leads": 0,
        "ctr": 0.0524,
        "cpl": null
      },
      {
        "text": "software de e-procurement",
        "matchedKeyword": null,
        "impressions": 1335,
        "clicks": 40,
        "spend": 670.29,
        "leads": 0,
        "ctr": 0.03,
        "cpl": null
      },
      {
        "text": "outplan",
        "matchedKeyword": null,
        "impressions": 859,
        "clicks": 77,
        "spend": 644.71,
        "leads": 0,
        "ctr": 0.0896,
        "cpl": null
      },
      {
        "text": "software de compras",
        "matchedKeyword": null,
        "impressions": 1474,
        "clicks": 29,
        "spend": 268.14,
        "leads": 0,
        "ctr": 0.0197,
        "cpl": null
      }
    ],
    "keywordTabs": {
      "converters": [
        {
          "text": "outbuycenter",
          "matchedKeyword": null,
          "impressions": 2240,
          "clicks": 474,
          "spend": 3589.42,
          "leads": 10,
          "ctr": 0.2116,
          "cpl": 358.94,
          "category": "brand"
        },
        {
          "text": "nimbi",
          "matchedKeyword": null,
          "impressions": 4720,
          "clicks": 180,
          "spend": 2473.46,
          "leads": 7,
          "ctr": 0.0381,
          "cpl": 353.35,
          "category": "competitor"
        },
        {
          "text": "E-procurement",
          "matchedKeyword": null,
          "impressions": 3997,
          "clicks": 140,
          "spend": 2052.42,
          "leads": 5,
          "ctr": 0.035,
          "cpl": 410.48,
          "category": "bottomFunnel"
        },
        {
          "text": "portal de compras b2b",
          "matchedKeyword": null,
          "impressions": 414,
          "clicks": 32,
          "spend": 448.05,
          "leads": 1,
          "ctr": 0.0773,
          "cpl": 448.05,
          "category": "bottomFunnel"
        },
        {
          "text": "sistema de gestão de fornecedores",
          "matchedKeyword": null,
          "impressions": 763,
          "clicks": 30,
          "spend": 427.17,
          "leads": 1,
          "ctr": 0.0393,
          "cpl": 427.17,
          "category": "bottomFunnel"
        },
        {
          "text": "software srm",
          "matchedKeyword": null,
          "impressions": 708,
          "clicks": 14,
          "spend": 268.13,
          "leads": 1,
          "ctr": 0.0198,
          "cpl": 268.13,
          "category": "bottomFunnel"
        },
        {
          "text": "proxpect",
          "matchedKeyword": null,
          "impressions": 987,
          "clicks": 14,
          "spend": 209.25,
          "leads": 1,
          "ctr": 0.0142,
          "cpl": 209.25,
          "category": "competitor"
        },
        {
          "text": "Ferramenta de E-procurement",
          "matchedKeyword": null,
          "impressions": 191,
          "clicks": 7,
          "spend": 194.02,
          "leads": 1,
          "ctr": 0.0366,
          "cpl": 194.02,
          "category": "bottomFunnel"
        }
      ],
      "bottomFunnel": [
        {
          "text": "E-procurement",
          "matchedKeyword": null,
          "impressions": 3997,
          "clicks": 140,
          "spend": 2052.42,
          "leads": 5,
          "ctr": 0.035,
          "cpl": 410.48,
          "category": "bottomFunnel"
        },
        {
          "text": "portal de compras b2b",
          "matchedKeyword": null,
          "impressions": 414,
          "clicks": 32,
          "spend": 448.05,
          "leads": 1,
          "ctr": 0.0773,
          "cpl": 448.05,
          "category": "bottomFunnel"
        },
        {
          "text": "sistema de gestão de fornecedores",
          "matchedKeyword": null,
          "impressions": 763,
          "clicks": 30,
          "spend": 427.17,
          "leads": 1,
          "ctr": 0.0393,
          "cpl": 427.17,
          "category": "bottomFunnel"
        },
        {
          "text": "software srm",
          "matchedKeyword": null,
          "impressions": 708,
          "clicks": 14,
          "spend": 268.13,
          "leads": 1,
          "ctr": 0.0198,
          "cpl": 268.13,
          "category": "bottomFunnel"
        },
        {
          "text": "Ferramenta de E-procurement",
          "matchedKeyword": null,
          "impressions": 191,
          "clicks": 7,
          "spend": 194.02,
          "leads": 1,
          "ctr": 0.0366,
          "cpl": 194.02,
          "category": "bottomFunnel"
        },
        {
          "text": "sistema de e-procurement",
          "matchedKeyword": null,
          "impressions": 1049,
          "clicks": 55,
          "spend": 830.24,
          "leads": 0,
          "ctr": 0.0524,
          "cpl": null,
          "category": "bottomFunnel"
        },
        {
          "text": "software de e-procurement",
          "matchedKeyword": null,
          "impressions": 1335,
          "clicks": 40,
          "spend": 670.29,
          "leads": 0,
          "ctr": 0.03,
          "cpl": null,
          "category": "bottomFunnel"
        },
        {
          "text": "software de compras",
          "matchedKeyword": null,
          "impressions": 1474,
          "clicks": 29,
          "spend": 268.14,
          "leads": 0,
          "ctr": 0.0197,
          "cpl": null,
          "category": "bottomFunnel"
        },
        {
          "text": "sistema de compras para empresas",
          "matchedKeyword": null,
          "impressions": 323,
          "clicks": 4,
          "spend": 31.93,
          "leads": 0,
          "ctr": 0.0124,
          "cpl": null,
          "category": "bottomFunnel"
        }
      ],
      "competitors": [
        {
          "text": "nimbi",
          "matchedKeyword": null,
          "impressions": 4720,
          "clicks": 180,
          "spend": 2473.46,
          "leads": 7,
          "ctr": 0.0381,
          "cpl": 353.35,
          "category": "competitor"
        },
        {
          "text": "proxpect",
          "matchedKeyword": null,
          "impressions": 987,
          "clicks": 14,
          "spend": 209.25,
          "leads": 1,
          "ctr": 0.0142,
          "cpl": 209.25,
          "category": "competitor"
        },
        {
          "text": "paradigma wbc",
          "matchedKeyword": null,
          "impressions": 11,
          "clicks": 1,
          "spend": 42.96,
          "leads": 0,
          "ctr": 0.0909,
          "cpl": null,
          "category": "competitor"
        },
        {
          "text": "nimbi eprocurement",
          "matchedKeyword": null,
          "impressions": 1,
          "clicks": 1,
          "spend": 7.54,
          "leads": 0,
          "ctr": 1,
          "cpl": null,
          "category": "competitor"
        }
      ]
    },
    "trackedSpend": 12270.43,
    "trackedLeads": 27,
    "spendCoverage": 0.5804,
    "leadCoverage": 0.6279
  },
  "conversionIntegrity": {
    "definition": "Lead = ação SUBMIT_LEAD_FORM registrada pelo Google Ads.",
    "pageViewAction": {
      "name": "PageView",
      "status": "ENABLED",
      "primary": true,
      "included": true,
      "countingType": "MANY_PER_CLICK"
    },
    "excludedPlatformConversions": 67,
    "firstLeadDate": "2026-03-18",
    "note": "PageView inflou a coluna Conversões em fevereiro e março. O dashboard recalcula leads pelas ações de envio de formulário e separa site de formulário hospedado pelo Google."
  },
  "highlights": [
    {
      "tone": "positive",
      "title": "Abr 2026: maior volume",
      "body": "11 leads, com custo médio de R$ 280,19 por lead."
    },
    {
      "tone": "positive",
      "title": "Abr 2026: melhor eficiência",
      "body": "Cada lead custou R$ 280,19 e 4,5% dos cliques viraram lead."
    },
    {
      "tone": "negative",
      "title": "Julho–agosto: queda depois do clique",
      "body": "Os cliques variaram 3,3% em agosto, mas os leads caíram 75%."
    },
    {
      "tone": "caution",
      "title": "Setembro recuperou volume, por canais diferentes",
      "body": "2 leads vieram do site e 3 do formulário hospedado pelo Google."
    }
  ],
  "pendingInputs": [
    "Datas em que cada versão da landing page entrou no ar; as revisões reutilizaram a mesma URL e não podem ser separadas pelo Google Ads.",
    "Status de qualificação e origem comercial dos 43 leads para calcular CPL qualificado e comparar site versus formulário hospedado."
  ]
};
